/**
 * PrivacyPolicy Page
 * Legally required content explaining data usage and the entertainment nature of the app.
 */

import React from 'react';
import styled from 'styled-components';
import { useNavigate } from 'react-router-dom';
import { theme } from '@/styles/theme';
import { ArrowLeft } from 'lucide-react';
import Layout from '@/components/layout/Layout';

const PrivacyPolicy: React.FC = () => {
  const navigate = useNavigate();

  return (
    <Layout>
      <Container>
        <Header>
          <BackButton onClick={() => navigate(-1)}>
            <ArrowLeft size={24} />
          </BackButton>
          <Title>Privacy & Terms</Title>
        </Header>

        <Content>
          <Section>
            <SectionTitle>1. Data Collection</SectionTitle>
            <Text>
              The "Mental Age Test" app stores your profile information (Name, Age, Gender) and test results locally on your device. We do not transmit this data to our servers unless specifically required for cloud-sync features (if enabled).
            </Text>
          </Section>

          <Section>
            <SectionTitle>2. AI Processing</SectionTitle>
            <Text>
              We use OpenRouter API to generate personality insights. Your quiz answers are sent anonymously to the AI model to provide personalized feedback. No personally identifiable information is shared with third-party AI providers.
            </Text>
          </Section>

          <Section>
            <SectionTitle>3. Entertainment Disclaimer</SectionTitle>
            <HighlightBox>
              This application is designed strictly for entertainment purposes. The "Mental Age" score and "Personality Analysis" are generated by AI based on subjective responses and do not constitute a scientific, medical, or psychological evaluation.
            </HighlightBox>
          </Section>

          <Section>
            <SectionTitle>4. Advertising</SectionTitle>
            <Text>
              We use third-party advertising partners to keep this app free. These partners may collect anonymous device identifiers to show relevant ads.
            </Text>
          </Section>

          <Section>
            <SectionTitle>5. User Rights</SectionTitle>
            <Text>
              You can delete all your stored data at any time through the "Settings" menu by selecting "Clear All Data".
            </Text>
          </Section>
        </Content>
      </Container>
    </Layout>
  );
};

const Container = styled.div`
  padding: 24px;
  max-width: 600px;
  margin: 0 auto;
  padding-bottom: 60px;
`;

const Header = styled.div`
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 32px;
`;

const BackButton = styled.button`
  color: ${theme.colors.textMain};
`;

const Title = styled.h1`
  font-size: ${theme.typography.fontSizes.xl};
`;

const Content = styled.div`
  display: flex;
  flex-direction: column;
  gap: 24px;
`;

const Section = styled.section``;

const SectionTitle = styled.h3`
  font-size: ${theme.typography.fontSizes.md};
  color: ${theme.colors.accent};
  margin-bottom: 12px;
`;

const Text = styled.p`
  font-size: ${theme.typography.fontSizes.sm};
  color: ${theme.colors.textSecondary};
  line-height: 1.6;
`;

const HighlightBox = styled.div`
  padding: 16px;
  background: rgba(168, 85, 247, 0.1);
  border-left: 4px solid ${theme.colors.accent};
  border-radius: 4px;
  font-size: ${theme.typography.fontSizes.sm};
  color: ${theme.colors.textMain};
  font-style: italic;
  line-height: 1.6;
`;

export default PrivacyPolicy;
